module.exports = {
  version: "0.2",
  language: "en",
  words: [
    "aran",
    "classfication",
    "citty",
    "consola",
    "dominik",
    "datagen",
    "drawio",
    "hono",
    "outdir",
    "tegaki",
    "ubugeeei",
    "unicodegen",
    "xmls",
  ],
  dictionaries: [
    "softwareTerms",
    "misc",
    "companies",
    "typescript",
    "node",
    "html",
    "css",
    "fonts",
    "filetypes",
    "npm",
  ],
  ignorePaths: [
    "**/dist/*",
    "**/bin/*",
    "**/node_modules/*",
    "**/.git/*",
    "**/.gitignore",
    "**/.vscode/*",
    "**/pnpm-lock.yaml",
    "**/*.drawio",
    "**/*.svg",
    "**/*.png",
    "**/*.jpeg",
    "**/*.otf",
  ],
};
