module.exports = {
  version: "0.2",
  language: "en",
  words: ["aran", "classfication", "dominik", "drawio", "hono", "outdir", "tegaki", "ubugeeei", "xmls"],
  dictionaries: [
    "softwareTerms",
    "misc",
    "companies",
    "typescript",
    "node",
    "html",
    "css",
    "fonts",
    "filetypes",
    "npm",
  ],
  ignorePaths: [
    "**/dist/*",
    "**/node_modules/*",
    "**/.git/*",
    "**/.gitignore",
    "**/.vscode/*",
    "**/pnpm-lock.yaml",
    "**/*.drawio",
    "**/*.svg",
    "**/*.png",
    "**/*.jpeg",
    "**/*.otf",
  ],
};
